In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from config import google_api_key
import json
import requests
import sqlite3
from sqlalchemy import create_engine

## 1. Extract city and state based on zip code

### 1.1. Loading raw data

In [2]:
# Load dataset
df = pd.read_csv("../data/lender_data.csv", skiprows=1, dtype={'Zip': object})

# Drop rows that are all NaN's
df = df.dropna(how='all')
df.head()

Deal ID  Lender ID    Zip  City  State Multifamily Subtype Built   Units  \
0  14454.0       19.0  92626   NaN    NaN              Garden  1990    24.0   
1  20421.0       19.0  91406   NaN    NaN              Garden  1962    15.0   
2  24298.0       50.0  70122   NaN    NaN              Garden  2009   164.0   
3   2853.0       19.0  90046   NaN    NaN              Garden  1957    11.0   
4   3023.0       51.0  11215   NaN    NaN              Garden  2002    13.0   

  Original Loan  Note Rate  Loan Term (Original) Appraised Value  \
0      1,720,000      5.8%                 180.0       3,500,000   
1        500,000      5.3%                 180.0       1,525,000   
2        250,000      6.9%                 120.0       4,187,586   
3        805,000      5.2%                 180.0       2,450,000   
4      1,600,000      6.5%                 120.0       3,112,000   

  Maturity Date      UPB Amort DSvc  Orig Amort  IO Period  Unnamed: 17  \
0        2/1/19   28,379     14,292       180.0        0.0          NaN   
1       12/1/19   46,916      4,022       180.0        0.0          NaN   
2        1/1/21   67,161      2,892       120.0        0.0          NaN   
3        8/1/20  123,314      6,450       180.0        0.0          NaN   
4        7/1/19  124,669     18,200       120.0        0.0          NaN   

   Unnamed: 18  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [3]:
# Drop meaningless columns "Unnamed: 17", "Unnamed: 18"
df = df.drop(columns=[col for col in df.columns.tolist() if 'Unnamed' in col])

# Overview of dataset
print(f"There are {df.shape[0]} rows in the dataset.")

# Number of missing values in each column
print("Number of missing values in each column:")
df.isnull().sum()

There are 29130 rows in the dataset.
Number of missing values in each column:


Deal ID                     0
Lender ID                   0
Zip                         0
City                    29130
State                   29130
Multifamily Subtype         0
Built                       0
 Units                      0
Original Loan               0
Note Rate                   0
Loan Term (Original)        0
Appraised Value             0
Maturity Date               0
UPB                         0
Amort DSvc                  0
Orig Amort                  0
IO Period                   0
dtype: int64

In [4]:
# Number of unique values
print("Number of unique values in each column:")
df.nunique()

Number of unique values in each column:


Deal ID                 29128
Lender ID                  58
Zip                      6974
City                        0
State                       0
Multifamily Subtype        20
Built                     165
 Units                    886
Original Loan           12396
Note Rate                  77
Loan Term (Original)       90
Appraised Value          7022
Maturity Date             387
UPB                     25261
Amort DSvc              25552
Orig Amort                 45
IO Period                  35
dtype: int64

### 1.2. Fill in city and state blanks

Use [Google Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro) to get the City and State for each deal from the Zip Code provided.

In [5]:
# Construct API query
base_url = "https://maps.googleapis.com/maps/api/geocode/json"
params = {"key": google_api_key}

In [6]:
# Create a list of unique zip code to look up
zipcode_unique = df['Zip'].unique().tolist()

In [7]:
# results_list = []
# for index, zipcode in enumerate(zipcode_unique):
    
#     target_zipcode = zipcode
#     params['components'] = f"country:US|postal_code:{target_zipcode}"
#     print(f"Retrieving Results for Index {index}: {target_zipcode}.")

#     response = requests.get(base_url, params=params).json()
#     results = response.get('results')
#     results_list.append(results)

Retrieving Results for Index 0: 92626.
Retrieving Results for Index 1: 91406.
Retrieving Results for Index 2: 70122.
Retrieving Results for Index 3: 90046.
Retrieving Results for Index 4: 11215.
Retrieving Results for Index 5: 66062.
Retrieving Results for Index 6: 90245.
Retrieving Results for Index 7: 13601.
Retrieving Results for Index 8: 95117.
Retrieving Results for Index 9: 31806.
Retrieving Results for Index 10: 90068.
Retrieving Results for Index 11: 90262.
Retrieving Results for Index 12: 31096.
Retrieving Results for Index 13: 31002.
Retrieving Results for Index 14: 91204.
Retrieving Results for Index 15: 30428.
Retrieving Results for Index 16: 30411.
Retrieving Results for Index 17: 31824.
Retrieving Results for Index 18: 02062.
Retrieving Results for Index 19: 31091.
Retrieving Results for Index 20: 30810.
Retrieving Results for Index 21: 83631.
Retrieving Results for Index 22: 98208.
Retrieving Results for Index 23: 83318.
Retrieving Results for Index 24: 31650.
Retrieving

Retrieving Results for Index 203: 97383.
Retrieving Results for Index 204: 90301.
Retrieving Results for Index 205: 45219.
Retrieving Results for Index 206: 55428.
Retrieving Results for Index 207: 72160.
Retrieving Results for Index 208: 28083.
Retrieving Results for Index 209: 90027.
Retrieving Results for Index 210: 90621.
Retrieving Results for Index 211: 78208.
Retrieving Results for Index 212: 93033.
Retrieving Results for Index 213: 92109.
Retrieving Results for Index 214: 70805.
Retrieving Results for Index 215: 91706.
Retrieving Results for Index 216: 98662.
Retrieving Results for Index 217: 90815.
Retrieving Results for Index 218: 71115.
Retrieving Results for Index 219: 61820.
Retrieving Results for Index 220: 07050.
Retrieving Results for Index 221: 92025.
Retrieving Results for Index 222: 90804.
Retrieving Results for Index 223: 60415.
Retrieving Results for Index 224: 60506.
Retrieving Results for Index 225: 92105.
Retrieving Results for Index 226: 97502.
Retrieving Resul

Retrieving Results for Index 403: 92110.
Retrieving Results for Index 404: 90250.
Retrieving Results for Index 405: 63110.
Retrieving Results for Index 406: 36567.
Retrieving Results for Index 407: 01040.
Retrieving Results for Index 408: 07042.
Retrieving Results for Index 409: 94610.
Retrieving Results for Index 410: 39846.
Retrieving Results for Index 411: 02904.
Retrieving Results for Index 412: 44112.
Retrieving Results for Index 413: 92345.
Retrieving Results for Index 414: 97322.
Retrieving Results for Index 415: 83854.
Retrieving Results for Index 416: 55435.
Retrieving Results for Index 417: 74074.
Retrieving Results for Index 418: 83706.
Retrieving Results for Index 419: 60659.
Retrieving Results for Index 420: 11238.
Retrieving Results for Index 421: 78578.
Retrieving Results for Index 422: 27405.
Retrieving Results for Index 423: 11216.
Retrieving Results for Index 424: 16001.
Retrieving Results for Index 425: 08609.
Retrieving Results for Index 426: 44109.
Retrieving Resul

Retrieving Results for Index 603: 96815.
Retrieving Results for Index 604: 30533.
Retrieving Results for Index 605: 29527.
Retrieving Results for Index 606: 32304.
Retrieving Results for Index 607: 71602.
Retrieving Results for Index 608: 84041.
Retrieving Results for Index 609: 97232.
Retrieving Results for Index 610: 28625.
Retrieving Results for Index 611: 85014.
Retrieving Results for Index 612: 98363.
Retrieving Results for Index 613: 98407.
Retrieving Results for Index 614: 21230.
Retrieving Results for Index 615: 85719.
Retrieving Results for Index 616: 48174.
Retrieving Results for Index 617: 01833.
Retrieving Results for Index 618: 80220.
Retrieving Results for Index 619: 98368.
Retrieving Results for Index 620: 35243.
Retrieving Results for Index 621: 07501.
Retrieving Results for Index 622: 99501.
Retrieving Results for Index 623: 33135.
Retrieving Results for Index 624: 94116.
Retrieving Results for Index 625: 84102.
Retrieving Results for Index 626: 14607.
Retrieving Resul

Retrieving Results for Index 804: 32536.
Retrieving Results for Index 805: 97401.
Retrieving Results for Index 806: 32901.
Retrieving Results for Index 807: 37160.
Retrieving Results for Index 808: 32803.
Retrieving Results for Index 809: 97702.
Retrieving Results for Index 810: 02134.
Retrieving Results for Index 811: 54409.
Retrieving Results for Index 812: 47150.
Retrieving Results for Index 813: 94121.
Retrieving Results for Index 814: 92655.
Retrieving Results for Index 815: 27707.
Retrieving Results for Index 816: 32608.
Retrieving Results for Index 817: 91803.
Retrieving Results for Index 818: 57032.
Retrieving Results for Index 819: 97701.
Retrieving Results for Index 820: 07505.
Retrieving Results for Index 821: 29670.
Retrieving Results for Index 822: 70127.
Retrieving Results for Index 823: 11218.
Retrieving Results for Index 824: 04083.
Retrieving Results for Index 825: 90018.
Retrieving Results for Index 826: 91103.
Retrieving Results for Index 827: 93402.
Retrieving Resul

Retrieving Results for Index 1004: 10459.
Retrieving Results for Index 1005: 95240.
Retrieving Results for Index 1006: 74023.
Retrieving Results for Index 1007: 98026.
Retrieving Results for Index 1008: 06759.
Retrieving Results for Index 1009: 33990.
Retrieving Results for Index 1010: 53235.
Retrieving Results for Index 1011: 98370.
Retrieving Results for Index 1012: 24592.
Retrieving Results for Index 1013: 45431.
Retrieving Results for Index 1014: 11213.
Retrieving Results for Index 1015: 80918.
Retrieving Results for Index 1016: 94030.
Retrieving Results for Index 1017: 90037.
Retrieving Results for Index 1018: 85901.
Retrieving Results for Index 1019: 92335.
Retrieving Results for Index 1020: 06110.
Retrieving Results for Index 1021: 85021.
Retrieving Results for Index 1022: 91733.
Retrieving Results for Index 1023: 29910.
Retrieving Results for Index 1024: 25404.
Retrieving Results for Index 1025: 70403.
Retrieving Results for Index 1026: 75068.
Retrieving Results for Index 1027:

Retrieving Results for Index 1201: 34994.
Retrieving Results for Index 1202: 59105.
Retrieving Results for Index 1203: 28150.
Retrieving Results for Index 1204: 23901.
Retrieving Results for Index 1205: 78041.
Retrieving Results for Index 1206: 53549.
Retrieving Results for Index 1207: 73069.
Retrieving Results for Index 1208: 12543.
Retrieving Results for Index 1209: 29697.
Retrieving Results for Index 1210: 78501.
Retrieving Results for Index 1211: 92399.
Retrieving Results for Index 1212: 84117.
Retrieving Results for Index 1213: 93702.
Retrieving Results for Index 1214: 86323.
Retrieving Results for Index 1215: 65807.
Retrieving Results for Index 1216: 28312.
Retrieving Results for Index 1217: 90277.
Retrieving Results for Index 1218: 97367.
Retrieving Results for Index 1219: 11706.
Retrieving Results for Index 1220: 02188.
Retrieving Results for Index 1221: 75110.
Retrieving Results for Index 1222: 91791.
Retrieving Results for Index 1223: 45211.
Retrieving Results for Index 1224:

Retrieving Results for Index 1397: 75089.
Retrieving Results for Index 1398: 16438.
Retrieving Results for Index 1399: 39206.
Retrieving Results for Index 1400: 54601.
Retrieving Results for Index 1401: 27249.
Retrieving Results for Index 1402: 74055.
Retrieving Results for Index 1403: 44062.
Retrieving Results for Index 1404: 34608.
Retrieving Results for Index 1405: 50401.
Retrieving Results for Index 1406: 79936.
Retrieving Results for Index 1407: 57106.
Retrieving Results for Index 1408: 53072.
Retrieving Results for Index 1409: 14606.
Retrieving Results for Index 1410: 31520.
Retrieving Results for Index 1411: 97013.
Retrieving Results for Index 1412: 95003.
Retrieving Results for Index 1413: 36037.
Retrieving Results for Index 1414: 84106.
Retrieving Results for Index 1415: 55420.
Retrieving Results for Index 1416: 80621.
Retrieving Results for Index 1417: 30083.
Retrieving Results for Index 1418: 95062.
Retrieving Results for Index 1419: 48823.
Retrieving Results for Index 1420:

Retrieving Results for Index 1593: 72701.
Retrieving Results for Index 1594: 71901.
Retrieving Results for Index 1595: 80033.
Retrieving Results for Index 1596: 21078.
Retrieving Results for Index 1597: 12822.
Retrieving Results for Index 1598: 92111.
Retrieving Results for Index 1599: 93930.
Retrieving Results for Index 1600: 92866.
Retrieving Results for Index 1601: 79912.
Retrieving Results for Index 1602: 77833.
Retrieving Results for Index 1603: 97267.
Retrieving Results for Index 1604: 23503.
Retrieving Results for Index 1605: 37343.
Retrieving Results for Index 1606: 92027.
Retrieving Results for Index 1607: 89449.
Retrieving Results for Index 1608: 36542.
Retrieving Results for Index 1609: 53566.
Retrieving Results for Index 1610: 46410.
Retrieving Results for Index 1611: 72210.
Retrieving Results for Index 1612: 73159.
Retrieving Results for Index 1613: 42086.
Retrieving Results for Index 1614: 60620.
Retrieving Results for Index 1615: 12110.
Retrieving Results for Index 1616:

Retrieving Results for Index 1790: 85714.
Retrieving Results for Index 1791: 78028.
Retrieving Results for Index 1792: 44827.
Retrieving Results for Index 1793: 52761.
Retrieving Results for Index 1794: 70807.
Retrieving Results for Index 1795: 14850.
Retrieving Results for Index 1796: 12210.
Retrieving Results for Index 1797: 72034.
Retrieving Results for Index 1798: 31792.
Retrieving Results for Index 1799: 99503.
Retrieving Results for Index 1800: 53717.
Retrieving Results for Index 1801: 14221.
Retrieving Results for Index 1802: 95050.
Retrieving Results for Index 1803: 29360.
Retrieving Results for Index 1804: 85711.
Retrieving Results for Index 1805: 91301.
Retrieving Results for Index 1806: 66061.
Retrieving Results for Index 1807: 89015.
Retrieving Results for Index 1808: 93210.
Retrieving Results for Index 1809: 75428.
Retrieving Results for Index 1810: 11782.
Retrieving Results for Index 1811: 77502.
Retrieving Results for Index 1812: 02911.
Retrieving Results for Index 1813:

Retrieving Results for Index 1986: 54911.
Retrieving Results for Index 1987: 96002.
Retrieving Results for Index 1988: 15626.
Retrieving Results for Index 1989: 95370.
Retrieving Results for Index 1990: 68801.
Retrieving Results for Index 1991: 14202.
Retrieving Results for Index 1992: 16242.
Retrieving Results for Index 1993: 78520.
Retrieving Results for Index 1994: 95382.
Retrieving Results for Index 1995: 53121.
Retrieving Results for Index 1996: 02895.
Retrieving Results for Index 1997: 33712.
Retrieving Results for Index 1998: 31326.
Retrieving Results for Index 1999: 48238.
Retrieving Results for Index 2000: 16701.
Retrieving Results for Index 2001: 05401.
Retrieving Results for Index 2002: 78757.
Retrieving Results for Index 2003: 84601.
Retrieving Results for Index 2004: 33511.
Retrieving Results for Index 2005: 84119.
Retrieving Results for Index 2006: 66047.
Retrieving Results for Index 2007: 78840.
Retrieving Results for Index 2008: 78586.
Retrieving Results for Index 2009:

Retrieving Results for Index 2183: 37043.
Retrieving Results for Index 2184: 77642.
Retrieving Results for Index 2185: 90024.
Retrieving Results for Index 2186: 97121.
Retrieving Results for Index 2187: 77346.
Retrieving Results for Index 2188: 19365.
Retrieving Results for Index 2189: 98188.
Retrieving Results for Index 2190: 13045.
Retrieving Results for Index 2191: 30736.
Retrieving Results for Index 2192: 13207.
Retrieving Results for Index 2193: 64150.
Retrieving Results for Index 2194: 14075.
Retrieving Results for Index 2195: 77015.
Retrieving Results for Index 2196: 39056.
Retrieving Results for Index 2197: 06824.
Retrieving Results for Index 2198: 45414.
Retrieving Results for Index 2199: 48047.
Retrieving Results for Index 2200: 27344.
Retrieving Results for Index 2201: 98383.
Retrieving Results for Index 2202: 29316.
Retrieving Results for Index 2203: 34479.
Retrieving Results for Index 2204: 92203.
Retrieving Results for Index 2205: 74146.
Retrieving Results for Index 2206:

Retrieving Results for Index 2379: 21204.
Retrieving Results for Index 2380: 32607.
Retrieving Results for Index 2381: 01089.
Retrieving Results for Index 2382: 55125.
Retrieving Results for Index 2383: 48430.
Retrieving Results for Index 2384: 11729.
Retrieving Results for Index 2385: 79119.
Retrieving Results for Index 2386: 90680.
Retrieving Results for Index 2387: 48108.
Retrieving Results for Index 2388: 47408.
Retrieving Results for Index 2389: 88007.
Retrieving Results for Index 2390: 12603.
Retrieving Results for Index 2391: 33609.
Retrieving Results for Index 2392: 64116.
Retrieving Results for Index 2393: 58103.
Retrieving Results for Index 2394: 63113.
Retrieving Results for Index 2395: 97217.
Retrieving Results for Index 2396: 18704.
Retrieving Results for Index 2397: 94519.
Retrieving Results for Index 2398: 66046.
Retrieving Results for Index 2399: 43220.
Retrieving Results for Index 2400: 48640.
Retrieving Results for Index 2401: 70123.
Retrieving Results for Index 2402:

Retrieving Results for Index 2575: 68521.
Retrieving Results for Index 2576: 30318.
Retrieving Results for Index 2577: 59802.
Retrieving Results for Index 2578: 93277.
Retrieving Results for Index 2579: 75080.
Retrieving Results for Index 2580: 37013.
Retrieving Results for Index 2581: 91324.
Retrieving Results for Index 2582: 43081.
Retrieving Results for Index 2583: 29108.
Retrieving Results for Index 2584: 64109.
Retrieving Results for Index 2585: 72404.
Retrieving Results for Index 2586: 47006.
Retrieving Results for Index 2587: 34208.
Retrieving Results for Index 2588: 46350.
Retrieving Results for Index 2589: 03458.
Retrieving Results for Index 2590: 39705.
Retrieving Results for Index 2591: 19107.
Retrieving Results for Index 2592: 52314.
Retrieving Results for Index 2593: 85750.
Retrieving Results for Index 2594: 45220.
Retrieving Results for Index 2595: 60471.
Retrieving Results for Index 2596: 30253.
Retrieving Results for Index 2597: 32763.
Retrieving Results for Index 2598:

Retrieving Results for Index 2771: 15110.
Retrieving Results for Index 2772: 43302.
Retrieving Results for Index 2773: 20904.
Retrieving Results for Index 2774: 77074.
Retrieving Results for Index 2775: 63128.
Retrieving Results for Index 2776: 93110.
Retrieving Results for Index 2777: 85390.
Retrieving Results for Index 2778: 64079.
Retrieving Results for Index 2779: 28211.
Retrieving Results for Index 2780: 71104.
Retrieving Results for Index 2781: 94954.
Retrieving Results for Index 2782: 89030.
Retrieving Results for Index 2783: 95490.
Retrieving Results for Index 2784: 77099.
Retrieving Results for Index 2785: 22030.
Retrieving Results for Index 2786: 21001.
Retrieving Results for Index 2787: 37209.
Retrieving Results for Index 2788: 49015.
Retrieving Results for Index 2789: 95076.
Retrieving Results for Index 2790: 35803.
Retrieving Results for Index 2791: 53713.
Retrieving Results for Index 2792: 38614.
Retrieving Results for Index 2793: 75233.
Retrieving Results for Index 2794:

Retrieving Results for Index 2967: 55616.
Retrieving Results for Index 2968: 63367.
Retrieving Results for Index 2969: 98409.
Retrieving Results for Index 2970: 92395.
Retrieving Results for Index 2971: 33908.
Retrieving Results for Index 2972: 95661.
Retrieving Results for Index 2973: 27612.
Retrieving Results for Index 2974: 81650.
Retrieving Results for Index 2975: 12833.
Retrieving Results for Index 2976: 68127.
Retrieving Results for Index 2977: 32934.
Retrieving Results for Index 2978: 53045.
Retrieving Results for Index 2979: 66611.
Retrieving Results for Index 2980: 20024.
Retrieving Results for Index 2981: 66104.
Retrieving Results for Index 2982: 73122.
Retrieving Results for Index 2983: 48062.
Retrieving Results for Index 2984: 51104.
Retrieving Results for Index 2985: 33884.
Retrieving Results for Index 2986: 70072.
Retrieving Results for Index 2987: 52806.
Retrieving Results for Index 2988: 06704.
Retrieving Results for Index 2989: 68108.
Retrieving Results for Index 2990:

Retrieving Results for Index 3163: 07090.
Retrieving Results for Index 3164: 37379.
Retrieving Results for Index 3165: 14047.
Retrieving Results for Index 3166: 92029.
Retrieving Results for Index 3167: 16323.
Retrieving Results for Index 3168: 74127.
Retrieving Results for Index 3169: 55109.
Retrieving Results for Index 3170: 95334.
Retrieving Results for Index 3171: 48071.
Retrieving Results for Index 3172: 77471.
Retrieving Results for Index 3173: 32127.
Retrieving Results for Index 3174: 14004.
Retrieving Results for Index 3175: 77075.
Retrieving Results for Index 3176: 68164.
Retrieving Results for Index 3177: 55337.
Retrieving Results for Index 3178: 23320.
Retrieving Results for Index 3179: 95401.
Retrieving Results for Index 3180: 53545.
Retrieving Results for Index 3181: 97394.
Retrieving Results for Index 3182: 84074.
Retrieving Results for Index 3183: 37122.
Retrieving Results for Index 3184: 53081.
Retrieving Results for Index 3185: 60085.
Retrieving Results for Index 3186:

Retrieving Results for Index 3360: 06479.
Retrieving Results for Index 3361: 78233.
Retrieving Results for Index 3362: 75051.
Retrieving Results for Index 3363: 28117.
Retrieving Results for Index 3364: 10469.
Retrieving Results for Index 3365: 68124.
Retrieving Results for Index 3366: 28787.
Retrieving Results for Index 3367: 34450.
Retrieving Results for Index 3368: 85635.
Retrieving Results for Index 3369: 30606.
Retrieving Results for Index 3370: 80915.
Retrieving Results for Index 3371: 29851.
Retrieving Results for Index 3372: 93657.
Retrieving Results for Index 3373: 76301.
Retrieving Results for Index 3374: 11204.
Retrieving Results for Index 3375: 06405.
Retrieving Results for Index 3376: 78570.
Retrieving Results for Index 3377: 86322.
Retrieving Results for Index 3378: 91010.
Retrieving Results for Index 3379: 64119.
Retrieving Results for Index 3380: 34436.
Retrieving Results for Index 3381: 21085.
Retrieving Results for Index 3382: 78596.
Retrieving Results for Index 3383:

Retrieving Results for Index 3557: 75146.
Retrieving Results for Index 3558: 89408.
Retrieving Results for Index 3559: 33133.
Retrieving Results for Index 3560: 01420.
Retrieving Results for Index 3561: 87114.
Retrieving Results for Index 3562: 32708.
Retrieving Results for Index 3563: 37138.
Retrieving Results for Index 3564: 76140.
Retrieving Results for Index 3565: 11219.
Retrieving Results for Index 3566: 75235.
Retrieving Results for Index 3567: 12508.
Retrieving Results for Index 3568: 53818.
Retrieving Results for Index 3569: 78406.
Retrieving Results for Index 3570: 72956.
Retrieving Results for Index 3571: 75010.
Retrieving Results for Index 3572: 97479.
Retrieving Results for Index 3573: 32839.
Retrieving Results for Index 3574: 44110.
Retrieving Results for Index 3575: 76051.
Retrieving Results for Index 3576: 02893.
Retrieving Results for Index 3577: 91321.
Retrieving Results for Index 3578: 10032.
Retrieving Results for Index 3579: 78219.
Retrieving Results for Index 3580:

Retrieving Results for Index 3753: 23661.
Retrieving Results for Index 3754: 45449.
Retrieving Results for Index 3755: 91007.
Retrieving Results for Index 3756: 27701.
Retrieving Results for Index 3757: 27107.
Retrieving Results for Index 3758: 75766.
Retrieving Results for Index 3759: 17042.
Retrieving Results for Index 3760: 48216.
Retrieving Results for Index 3761: 23228.
Retrieving Results for Index 3762: 23294.
Retrieving Results for Index 3763: 70802.
Retrieving Results for Index 3764: 75220.
Retrieving Results for Index 3765: 01852.
Retrieving Results for Index 3766: 29418.
Retrieving Results for Index 3767: 95631.
Retrieving Results for Index 3768: 85304.
Retrieving Results for Index 3769: 30071.
Retrieving Results for Index 3770: 49855.
Retrieving Results for Index 3771: 75149.
Retrieving Results for Index 3772: 79102.
Retrieving Results for Index 3773: 85305.
Retrieving Results for Index 3774: 80020.
Retrieving Results for Index 3775: 71111.
Retrieving Results for Index 3776:

Retrieving Results for Index 3949: 20902.
Retrieving Results for Index 3950: 55414.
Retrieving Results for Index 3951: 40383.
Retrieving Results for Index 3952: 36701.
Retrieving Results for Index 3953: 37921.
Retrieving Results for Index 3954: 33774.
Retrieving Results for Index 3955: 46582.
Retrieving Results for Index 3956: 32065.
Retrieving Results for Index 3957: 06710.
Retrieving Results for Index 3958: 45503.
Retrieving Results for Index 3959: 27455.
Retrieving Results for Index 3960: 48840.
Retrieving Results for Index 3961: 15904.
Retrieving Results for Index 3962: 32244.
Retrieving Results for Index 3963: 48165.
Retrieving Results for Index 3964: 98498.
Retrieving Results for Index 3965: 72019.
Retrieving Results for Index 3966: 77486.
Retrieving Results for Index 3967: 37127.
Retrieving Results for Index 3968: 45305.
Retrieving Results for Index 3969: 18088.
Retrieving Results for Index 3970: 08902.
Retrieving Results for Index 3971: 48820.
Retrieving Results for Index 3972:

Retrieving Results for Index 4146: 46226.
Retrieving Results for Index 4147: 31601.
Retrieving Results for Index 4148: 79720.
Retrieving Results for Index 4149: 75116.
Retrieving Results for Index 4150: 76234.
Retrieving Results for Index 4151: 54720.
Retrieving Results for Index 4152: 76262.
Retrieving Results for Index 4153: 91750.
Retrieving Results for Index 4154: 76048.
Retrieving Results for Index 4155: 78621.
Retrieving Results for Index 4156: 94133.
Retrieving Results for Index 4157: 38106.
Retrieving Results for Index 4158: 93301.
Retrieving Results for Index 4159: 06360.
Retrieving Results for Index 4160: 23487.
Retrieving Results for Index 4161: 93312.
Retrieving Results for Index 4162: 14304.
Retrieving Results for Index 4163: 30317.
Retrieving Results for Index 4164: 10708.
Retrieving Results for Index 4165: 75248.
Retrieving Results for Index 4166: 54914.
Retrieving Results for Index 4167: 40504.
Retrieving Results for Index 4168: 93021.
Retrieving Results for Index 4169:

Retrieving Results for Index 4343: 03104.
Retrieving Results for Index 4344: 10801.
Retrieving Results for Index 4345: 44143.
Retrieving Results for Index 4346: 31502.
Retrieving Results for Index 4347: 33617.
Retrieving Results for Index 4348: 10314.
Retrieving Results for Index 4349: 33625.
Retrieving Results for Index 4350: 95242.
Retrieving Results for Index 4351: 95776.
Retrieving Results for Index 4352: 14589.
Retrieving Results for Index 4353: 72023.
Retrieving Results for Index 4354: 48015.
Retrieving Results for Index 4355: 95357.
Retrieving Results for Index 4356: 89117.
Retrieving Results for Index 4357: 40218.
Retrieving Results for Index 4358: 98424.
Retrieving Results for Index 4359: 48843.
Retrieving Results for Index 4360: 07110.
Retrieving Results for Index 4361: 70065.
Retrieving Results for Index 4362: 30062.
Retrieving Results for Index 4363: 04084.
Retrieving Results for Index 4364: 14464.
Retrieving Results for Index 4365: 57108.
Retrieving Results for Index 4366:

Retrieving Results for Index 4539: 07024.
Retrieving Results for Index 4540: 11763.
Retrieving Results for Index 4541: 91945.
Retrieving Results for Index 4542: 66214.
Retrieving Results for Index 4543: 20910.
Retrieving Results for Index 4544: 77066.
Retrieving Results for Index 4545: 78412.
Retrieving Results for Index 4546: 14031.
Retrieving Results for Index 4547: 34997.
Retrieving Results for Index 4548: 72209.
Retrieving Results for Index 4549: 11550.
Retrieving Results for Index 4550: 29710.
Retrieving Results for Index 4551: 33021.
Retrieving Results for Index 4552: 23702.
Retrieving Results for Index 4553: 54476.
Retrieving Results for Index 4554: 84116.
Retrieving Results for Index 4555: 55115.
Retrieving Results for Index 4556: 48444.
Retrieving Results for Index 4557: 95247.
Retrieving Results for Index 4558: 35064.
Retrieving Results for Index 4559: 34231.
Retrieving Results for Index 4560: 93611.
Retrieving Results for Index 4561: 77013.
Retrieving Results for Index 4562:

Retrieving Results for Index 4735: 23321.
Retrieving Results for Index 4736: 71291.
Retrieving Results for Index 4737: 54937.
Retrieving Results for Index 4738: 08648.
Retrieving Results for Index 4739: 08690.
Retrieving Results for Index 4740: 75253.
Retrieving Results for Index 4741: 89005.
Retrieving Results for Index 4742: 19116.
Retrieving Results for Index 4743: 14904.
Retrieving Results for Index 4744: 85205.
Retrieving Results for Index 4745: 21017.
Retrieving Results for Index 4746: 48134.
Retrieving Results for Index 4747: 33778.
Retrieving Results for Index 4748: 21208.
Retrieving Results for Index 4749: 77380.
Retrieving Results for Index 4750: 55082.
Retrieving Results for Index 4751: 95832.
Retrieving Results for Index 4752: 30106.
Retrieving Results for Index 4753: 91711.
Retrieving Results for Index 4754: 43119.
Retrieving Results for Index 4755: 90220.
Retrieving Results for Index 4756: 38114.
Retrieving Results for Index 4757: 39560.
Retrieving Results for Index 4758:

Retrieving Results for Index 4931: 77351.
Retrieving Results for Index 4932: 44906.
Retrieving Results for Index 4933: 28092.
Retrieving Results for Index 4934: 68046.
Retrieving Results for Index 4935: 85303.
Retrieving Results for Index 4936: 47710.
Retrieving Results for Index 4937: 77477.
Retrieving Results for Index 4938: 98354.
Retrieving Results for Index 4939: 14428.
Retrieving Results for Index 4940: 27517.
Retrieving Results for Index 4941: 78415.
Retrieving Results for Index 4942: 98273.
Retrieving Results for Index 4943: 92879.
Retrieving Results for Index 4944: 07728.
Retrieving Results for Index 4945: 34232.
Retrieving Results for Index 4946: 62959.
Retrieving Results for Index 4947: 27858.
Retrieving Results for Index 4948: 33324.
Retrieving Results for Index 4949: 08054.
Retrieving Results for Index 4950: 75159.
Retrieving Results for Index 4951: 71303.
Retrieving Results for Index 4952: 78247.
Retrieving Results for Index 4953: 13104.
Retrieving Results for Index 4954:

Retrieving Results for Index 5127: 15219.
Retrieving Results for Index 5128: 98683.
Retrieving Results for Index 5129: 01742.
Retrieving Results for Index 5130: 80503.
Retrieving Results for Index 5131: 32507.
Retrieving Results for Index 5132: 81631.
Retrieving Results for Index 5133: 76137.
Retrieving Results for Index 5134: 46628.
Retrieving Results for Index 5135: 25064.
Retrieving Results for Index 5136: 74137.
Retrieving Results for Index 5137: 18702.
Retrieving Results for Index 5138: 65202.
Retrieving Results for Index 5139: 75181.
Retrieving Results for Index 5140: 84058.
Retrieving Results for Index 5141: 78224.
Retrieving Results for Index 5142: 80435.
Retrieving Results for Index 5143: 92582.
Retrieving Results for Index 5144: 89434.
Retrieving Results for Index 5145: 11738.
Retrieving Results for Index 5146: 60532.
Retrieving Results for Index 5147: 12019.
Retrieving Results for Index 5148: 64117.
Retrieving Results for Index 5149: 34104.
Retrieving Results for Index 5150:

Retrieving Results for Index 5323: 49348.
Retrieving Results for Index 5324: 80238.
Retrieving Results for Index 5325: 93434.
Retrieving Results for Index 5326: 11434.
Retrieving Results for Index 5327: 97361.
Retrieving Results for Index 5328: 89081.
Retrieving Results for Index 5329: 33618.
Retrieving Results for Index 5330: 54455.
Retrieving Results for Index 5331: 55126.
Retrieving Results for Index 5332: 02914.
Retrieving Results for Index 5333: 37772.
Retrieving Results for Index 5334: 93004.
Retrieving Results for Index 5335: 20001.
Retrieving Results for Index 5336: 07204.
Retrieving Results for Index 5337: 06517.
Retrieving Results for Index 5338: 70460.
Retrieving Results for Index 5339: 18509.
Retrieving Results for Index 5340: 93662.
Retrieving Results for Index 5341: 60091.
Retrieving Results for Index 5342: 63102.
Retrieving Results for Index 5343: 19127.
Retrieving Results for Index 5344: 76207.
Retrieving Results for Index 5345: 48317.
Retrieving Results for Index 5346:

Retrieving Results for Index 5519: 75964.
Retrieving Results for Index 5520: 55021.
Retrieving Results for Index 5521: 28372.
Retrieving Results for Index 5522: 23456.
Retrieving Results for Index 5523: 91104.
Retrieving Results for Index 5524: 41018.
Retrieving Results for Index 5525: 53024.
Retrieving Results for Index 5526: 15201.
Retrieving Results for Index 5527: 60521.
Retrieving Results for Index 5528: 94553.
Retrieving Results for Index 5529: 29909.
Retrieving Results for Index 5530: 11561.
Retrieving Results for Index 5531: 60193.
Retrieving Results for Index 5532: 30076.
Retrieving Results for Index 5533: 63070.
Retrieving Results for Index 5534: 10302.
Retrieving Results for Index 5535: 10305.
Retrieving Results for Index 5536: 97031.
Retrieving Results for Index 5537: 48178.
Retrieving Results for Index 5538: 76248.
Retrieving Results for Index 5539: 53105.
Retrieving Results for Index 5540: 33950.
Retrieving Results for Index 5541: 19003.
Retrieving Results for Index 5542:

Retrieving Results for Index 5715: 32701.
Retrieving Results for Index 5716: 08070.
Retrieving Results for Index 5717: 30152.
Retrieving Results for Index 5718: 19464.
Retrieving Results for Index 5719: 98019.
Retrieving Results for Index 5720: 25510.
Retrieving Results for Index 5721: 77064.
Retrieving Results for Index 5722: 03060.
Retrieving Results for Index 5723: 67401.
Retrieving Results for Index 5724: 78362.
Retrieving Results for Index 5725: 92663.
Retrieving Results for Index 5726: 30238.
Retrieving Results for Index 5727: 80530.
Retrieving Results for Index 5728: 95132.
Retrieving Results for Index 5729: 17013.
Retrieving Results for Index 5730: 91207.
Retrieving Results for Index 5731: 48382.
Retrieving Results for Index 5732: 15650.
Retrieving Results for Index 5733: 07016.
Retrieving Results for Index 5734: 63385.
Retrieving Results for Index 5735: 76244.
Retrieving Results for Index 5736: 80210.
Retrieving Results for Index 5737: 89128.
Retrieving Results for Index 5738:

Retrieving Results for Index 5911: 28269.
Retrieving Results for Index 5912: 72207.
Retrieving Results for Index 5913: 03857.
Retrieving Results for Index 5914: 96740.
Retrieving Results for Index 5915: 15137.
Retrieving Results for Index 5916: 64126.
Retrieving Results for Index 5917: 33055.
Retrieving Results for Index 5918: 74103.
Retrieving Results for Index 5919: 33160.
Retrieving Results for Index 5920: 78754.
Retrieving Results for Index 5921: 74132.
Retrieving Results for Index 5922: 27601.
Retrieving Results for Index 5923: 20851.
Retrieving Results for Index 5924: 33433.
Retrieving Results for Index 5925: 12189.
Retrieving Results for Index 5926: 32707.
Retrieving Results for Index 5927: 98043.
Retrieving Results for Index 5928: 63011.
Retrieving Results for Index 5929: 92807.
Retrieving Results for Index 5930: 99019.
Retrieving Results for Index 5931: 73102.
Retrieving Results for Index 5932: 98446.
Retrieving Results for Index 5933: 73013.
Retrieving Results for Index 5934:

Retrieving Results for Index 6107: 46122.
Retrieving Results for Index 6108: 85748.
Retrieving Results for Index 6109: 18508.
Retrieving Results for Index 6110: 02301.
Retrieving Results for Index 6111: 63021.
Retrieving Results for Index 6112: 48075.
Retrieving Results for Index 6113: 32730.
Retrieving Results for Index 6114: 60504.
Retrieving Results for Index 6115: 97351.
Retrieving Results for Index 6116: 32614.
Retrieving Results for Index 6117: 23114.
Retrieving Results for Index 6118: 23693.
Retrieving Results for Index 6119: 70817.
Retrieving Results for Index 6120: 34714.
Retrieving Results for Index 6121: 64158.
Retrieving Results for Index 6122: 83716.
Retrieving Results for Index 6123: 43209.
Retrieving Results for Index 6124: 35214.
Retrieving Results for Index 6125: 75024.
Retrieving Results for Index 6126: 33411.
Retrieving Results for Index 6127: 63124.
Retrieving Results for Index 6128: 85382.
Retrieving Results for Index 6129: 94015.
Retrieving Results for Index 6130:

Retrieving Results for Index 6303: 80465.
Retrieving Results for Index 6304: 94555.
Retrieving Results for Index 6305: 80026.
Retrieving Results for Index 6306: 15222.
Retrieving Results for Index 6307: 68510.
Retrieving Results for Index 6308: 40243.
Retrieving Results for Index 6309: 73108.
Retrieving Results for Index 6310: 92065.
Retrieving Results for Index 6311: 30338.
Retrieving Results for Index 6312: 59405.
Retrieving Results for Index 6313: 32311.
Retrieving Results for Index 6314: 32765.
Retrieving Results for Index 6315: 06810.
Retrieving Results for Index 6316: 49002.
Retrieving Results for Index 6317: 96753.
Retrieving Results for Index 6318: 01375.
Retrieving Results for Index 6319: 38680.
Retrieving Results for Index 6320: 77498.
Retrieving Results for Index 6321: 49428.
Retrieving Results for Index 6322: 98597.
Retrieving Results for Index 6323: 53142.
Retrieving Results for Index 6324: 95377.
Retrieving Results for Index 6325: 22408.
Retrieving Results for Index 6326:

Retrieving Results for Index 6499: 44502.
Retrieving Results for Index 6500: 46037.
Retrieving Results for Index 6501: 80921.
Retrieving Results for Index 6502: 37219.
Retrieving Results for Index 6503: 60040.
Retrieving Results for Index 6504: 32606.
Retrieving Results for Index 6505: 18966.
Retrieving Results for Index 6506: 20772.
Retrieving Results for Index 6507: 01970.
Retrieving Results for Index 6508: 21128.
Retrieving Results for Index 6509: 21108.
Retrieving Results for Index 6510: 29935.
Retrieving Results for Index 6511: 35223.
Retrieving Results for Index 6512: 92673.
Retrieving Results for Index 6513: 33484.
Retrieving Results for Index 6514: 02466.
Retrieving Results for Index 6515: 08205.
Retrieving Results for Index 6516: 51106.
Retrieving Results for Index 6517: 75048.
Retrieving Results for Index 6518: 91913.
Retrieving Results for Index 6519: 01060.
Retrieving Results for Index 6520: 77565.
Retrieving Results for Index 6521: 02840.
Retrieving Results for Index 6522:

Retrieving Results for Index 6695: 20120.
Retrieving Results for Index 6696: 76182.
Retrieving Results for Index 6697: 92590.
Retrieving Results for Index 6698: 98271.
Retrieving Results for Index 6699: 49321.
Retrieving Results for Index 6700: 08857.
Retrieving Results for Index 6701: 33705.
Retrieving Results for Index 6702: 20874.
Retrieving Results for Index 6703: 77005.
Retrieving Results for Index 6704: 30305.
Retrieving Results for Index 6705: 23510.
Retrieving Results for Index 6706: 11210.
Retrieving Results for Index 6707: 32250.
Retrieving Results for Index 6708: 92604.
Retrieving Results for Index 6709: 80923.
Retrieving Results for Index 6710: 01923.
Retrieving Results for Index 6711: 78738.
Retrieving Results for Index 6712: 89149.
Retrieving Results for Index 6713: 48105.
Retrieving Results for Index 6714: 22079.
Retrieving Results for Index 6715: 33027.
Retrieving Results for Index 6716: 76087.
Retrieving Results for Index 6717: 06042.
Retrieving Results for Index 6718:

Retrieving Results for Index 6891: 75028.
Retrieving Results for Index 6892: 92130.
Retrieving Results for Index 6893: 01605.
Retrieving Results for Index 6894: 95757.
Retrieving Results for Index 6895: 33435.
Retrieving Results for Index 6896: 95742.
Retrieving Results for Index 6897: 19129.
Retrieving Results for Index 6898: 94582.
Retrieving Results for Index 6899: 80924.
Retrieving Results for Index 6900: 92707.
Retrieving Results for Index 6901: 07470.
Retrieving Results for Index 6902: 33445.
Retrieving Results for Index 6903: 08096.
Retrieving Results for Index 6904: 44124.
Retrieving Results for Index 6905: 20817.
Retrieving Results for Index 6906: 01864.
Retrieving Results for Index 6907: 33018.
Retrieving Results for Index 6908: 34212.
Retrieving Results for Index 6909: 34119.
Retrieving Results for Index 6910: 22302.
Retrieving Results for Index 6911: 10038.
Retrieving Results for Index 6912: 91739.
Retrieving Results for Index 6913: 92612.
Retrieving Results for Index 6914:

In [8]:
# # Save results from API requests
# with open('zipcode_locations.json', 'w') as file_out:
#     json.dump(results_list, file_out)

In [7]:
# Load results from API requests
with open('temp/zipcode_locations.json', 'r') as file_in:
    zipcode_locations = json.load(file_in)

In [8]:
# Example API results
zipcode_locations[0]

[{'address_components': [{'long_name': '92626',
    'short_name': '92626',
    'types': ['postal_code']},
   {'long_name': 'Costa Mesa',
    'short_name': 'Costa Mesa',
    'types': ['locality', 'political']},
   {'long_name': 'Orange County',
    'short_name': 'Orange County',
    'types': ['administrative_area_level_2', 'political']},
   {'long_name': 'California',
    'short_name': 'CA',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'United States',
    'short_name': 'US',
    'types': ['country', 'political']}],
  'formatted_address': 'Costa Mesa, CA 92626, USA',
  'geometry': {'bounds': {'northeast': {'lat': 33.701975, 'lng': -117.8642701},
    'southwest': {'lat': 33.65618, 'lng': -117.946433}},
   'location': {'lat': 33.6834142, 'lng': -117.9073244},
   'location_type': 'APPROXIMATE',
   'viewport': {'northeast': {'lat': 33.701975, 'lng': -117.8642701},
    'southwest': {'lat': 33.65618, 'lng': -117.946433}}},
  'place_id': 'ChIJj4r82UHf3IARLQc40-4

According to the Google API documentation, `locality` is the address type that corresponds to city, and `administrative_area_level_1` is the address type that corresponds to state. However, sometimes `locality` does not exist in API results. Ideally, I would look up their exact city names. For the sake of time in this project, I'm going to use the second element in the `address_components` list as a proxy for the city. 

In [9]:
# Define a function to retrieve city and state information from API results of a particular zip code
def retrieve_city_state(index, results, zipcode_unique=zipcode_unique):
    '''
    Retrieve city and state information from API results
    INPUTS:
        index (int) - index of the particular zip code in `zipcode_unique`
        results (list) - list of API results of the particular zip code
        zipcode_unique (list) - list of unique zip code in the raw data
    OUTPUTS:
        city (str or NaN) - name of the corresponding city
        state (str or NaN) - name of the corresponding state
    '''
    city = np.nan
    state = np.nan
    if (results):
        address = results[0].get("address_components", "")
            
        for component in address:
            if 'locality' in component['types']:
                city = component.get("short_name", "") # protect from keyError
            elif 'administrative_area_level_1' in component['types']:
                state = component.get("short_name", "")
        
        # If locality does not exist in the API results
        if city is np.nan:
            city = address[1].get("short_name", "")
    else:
        print(f"No results for Index {index}: {zipcode_unique[index]}")
        
    return city, state

In [10]:
# Retrieve city and state information from API results
city_list = []
state_list = []

for index, results in enumerate(zipcode_locations):

    city, state = retrieve_city_state(index, results, zipcode_unique=zipcode_unique)
    city_list.append(city)
    state_list.append(state)

No results for Index 4623: 85220
No results for Index 5886: 85219
No results for Index 6020: 85223
No results for Index 6268: 85242


It appears that zip code 85220, 85219, 85223, and 85242 do not have valid city and state information. A closer look up on [USPS website](https://about.usps.com/postal-bulletin/2009/pb22259/html/info_001.htm) shows that these are the old codes and should be updated to the new ones: 85120, 85119, 85123, and 85142.

In [11]:
# Update zip codes and retrieve city and state info again
indices = [4623, 5886, 6020, 6268]
old_zipcode = [85220, 85219, 85223, 85242]
new_zipcode = [85120, 85119, 85123, 85142]

for i, index in enumerate(indices):
    
    # API request using the updated zip codes
    target_zipcode = new_zipcode[i]
    params['components'] = f"country:US|postal_code:{target_zipcode}"
    print(f"Retrieving Results for Index {index}: {target_zipcode}.")
    response = requests.get(base_url, params=params).json()
    results = response.get('results')
    
    # Retrieve city and state information
    city, state = retrieve_city_state(index, results, zipcode_unique=zipcode_unique)
    city_list[index] = city
    state_list[index] = state

Retrieving Results for Index 4623: 85120.
Retrieving Results for Index 5886: 85119.
Retrieving Results for Index 6020: 85123.
Retrieving Results for Index 6268: 85142.


In [12]:
# Combine zipcode, city, and state info into dictionary for easy query
zipcode_dict = {}
for index, zipcode in enumerate(zipcode_unique):
    zipcode_dict[zipcode] = {'city': city_list[index], 'state': state_list[index]}

In [13]:
# Fill in city and state info based on zip code
df['City'] = df['Zip'].apply(lambda x: zipcode_dict[x]['city'])
df['State'] = df['Zip'].apply(lambda x: zipcode_dict[x]['state'])
df.head()

Deal ID  Lender ID    Zip            City State Multifamily Subtype Built  \
0  14454.0       19.0  92626      Costa Mesa    CA              Garden  1990   
1  20421.0       19.0  91406     Los Angeles    CA              Garden  1962   
2  24298.0       50.0  70122     New Orleans    LA              Garden  2009   
3   2853.0       19.0  90046  West Hollywood    CA              Garden  1957   
4   3023.0       51.0  11215        Brooklyn    NY              Garden  2002   

    Units Original Loan  Note Rate  Loan Term (Original) Appraised Value  \
0    24.0      1,720,000      5.8%                 180.0       3,500,000   
1    15.0        500,000      5.3%                 180.0       1,525,000   
2   164.0        250,000      6.9%                 120.0       4,187,586   
3    11.0        805,000      5.2%                 180.0       2,450,000   
4    13.0      1,600,000      6.5%                 120.0       3,112,000   

  Maturity Date      UPB Amort DSvc  Orig Amort  IO Period  
0        2/1/19   28,379     14,292       180.0        0.0  
1       12/1/19   46,916      4,022       180.0        0.0  
2        1/1/21   67,161      2,892       120.0        0.0  
3        8/1/20  123,314      6,450       180.0        0.0  
4        7/1/19  124,669     18,200       120.0        0.0

In [14]:
# Sanity check
print(f"The dataset has {df['State'].nunique()} unique states.")

The dataset has 51 unique states.


### 1.3. Sanity check of the table

In [15]:
# Column name
df.columns

Index(['Deal ID', 'Lender ID', 'Zip', 'City', 'State', 'Multifamily Subtype',
       'Built', ' Units', 'Original Loan ', 'Note Rate',
       'Loan Term (Original)', 'Appraised Value', 'Maturity Date', 'UPB',
       'Amort DSvc', 'Orig Amort', 'IO Period'],
      dtype='object')

In [16]:
# Clean up column name
df.columns = [col.strip() for col in df.columns]
df.columns

Index(['Deal ID', 'Lender ID', 'Zip', 'City', 'State', 'Multifamily Subtype',
       'Built', 'Units', 'Original Loan', 'Note Rate', 'Loan Term (Original)',
       'Appraised Value', 'Maturity Date', 'UPB', 'Amort DSvc', 'Orig Amort',
       'IO Period'],
      dtype='object')

In [17]:
# Check the number of missing values in Lender ID
id_col = 'Lender ID'
missing_id = df.loc[(df[id_col].isnull()) | (df[id_col] == ""), id_col]
print(f"Number of missing values in Lender ID column: {missing_id.count()}")

Number of missing values in Lender ID column: 0


/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


In [18]:
# Check the number of missing values in other features
print("Number of missing values in each column:")
df.isnull().sum()

Number of missing values in each column:


Deal ID                 0
Lender ID               0
Zip                     0
City                    0
State                   0
Multifamily Subtype     0
Built                   0
Units                   0
Original Loan           0
Note Rate               0
Loan Term (Original)    0
Appraised Value         0
Maturity Date           0
UPB                     0
Amort DSvc              0
Orig Amort              0
IO Period               0
dtype: int64

In [19]:
# Drop duplicated rows
df = df.drop_duplicates()
print(f"Number of duplicated rows left: {df.duplicated().sum()}")

Number of duplicated rows left: 0


At this point, no missing value or duplicated row.

### 1.4. Save checkpoint

In [20]:
# Save dataframe into sqlite
engine = create_engine('sqlite:///../data/lender_data1.db')
df.to_sql('Lender', engine, index=False, if_exists='replace')
# engine.dispose()

# Save as a checkpoint
df.to_csv("temp/lender_checkpoint_1.csv", index=False)